### ISSUE TITLE
IESLoadHelper的saveAs2D函数的data参数

### ISSUE THREAD

**Issue by Anndy-Han** [ray-cast/ies#1]
请问IESLoadHelper的saveAs2D函数的data参数是干嘛的

**Comment by ray-cast** [comment]
data是灰度图片的指针，后面的参数是图片宽高

**Comment by ray-cast** [comment]
保存出来的是一个灰度图片，分别是1D的和2D的图片，转换成纹理后，使用方法是To use里的代码

**Comment by Anndy-Han** [comment]
![image](https://user-images.githubusercontent.com/29654838/75846667-fe2f6880-5e17-11ea-83bb-8ded2cfd3711.png)
转换的时候报错

**Comment by Anndy-Han** [comment]
saveAS2D方法怎么调用，按照1D的调用传参数失败



---原始邮件---
发件人: "Rui"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 中午12:23
收件人: "ray-cast/ies"<ies@noreply.github.com&gt;;
抄送: "Anndy"<751031007@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ray-cast/ies] IESLoadHelper的saveAs2D函数的data参数 (#1)



保存出来的是一个灰度图片，分别是1D的和2D的图片，转换成纹理后，使用方法是To use里的代码
